version: '2'
services:
    innovatismonolithicapplication-app:
        image: innovatismonolithicapplication
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://innovatismonolithicapplication-mysql:3306/innovatismonolithicapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9090:9090
    innovatismonolithicapplication-mysql:
        extends:
            file: mysql.yml
            service: innovatismonolithicapplication-mysql
